---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-app
  namespace: ssdevcloud
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload-container
        image: k8cluster1registry.azurecr.io/upload
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "info"
        - name: API_URL
          value: "https://upload.example.com"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: ssdevcloud
spec:
  selector:
    app: upload
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

